version: '2'
services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    ports:
      - ${ZOOKEEPER_PORT}:2181
  kafka:
    image: ${KAFKA_IMAGE}
    links:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      ZOOKEEPER_IP: ${HOST_IP}
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
  postgres:
    image: ${POSTGRES_IMAGE}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  postgrestest:
    image: ${POSTGRES_IMAGE}
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}

